config/routes.rb
Rails.application.routes.draw do
	

	###################### DEVISE CONTROLLERS ##############################
	
	devise_for :users, skip: [:sessions, :registrations]
	devise_scope :user do
		get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
		post 'sign_in', to: 'devise/sessions#create', as: :user_session
  	delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
		get 'cancel_registration', to: 'registrations#cancel', as: :cancel_user_registration
		get 'sign_up', to: 'registrations#new', as: :new_user_registration
		get 'change_password/:id', to: 'registrations#edit', as: :edit_user_registration
		patch '/change_password/:id', to: 'registrations#update', as: :update_edit_user_registration
		put '/user_registration', to: 'registrations#update'
		delete '/user_registration', to: 'registrations#destroy'
		post '/user_registration', to: 'registrations#create'
	end

	##################### USERS CONTROLLER ##############################

	resources :users, only: [:show]
	get '/delete_profiles', to: 'users#delete', as: :delete_profiles


	####################### PROFILES CONTROLLER ############################

	resources :profiles, only: [:show, :edit, :new, :destroy] do 
		member do
			patch 'edit', action: :update, :as => :update_edit
		end
	end
	post '/profiles/new', to: 'profiles#create', as: :update_new_profile
	get '/autocomplete', to: 'profiles#autocomplete', as: :autocomplete
	get '/discover', to: 'profiles#discover', as: :discover
	patch '/update_profile_img', to: 'profiles#update_profile_image', as: :update_profile_image
	get '/read_notifications', to: 'profiles#read_notifications', as: :read_notifications
	get '/welcome/:id', to: 'profiles#welcome', as: :welcome
	get '/set_pet_type', to: 'profiles#set_pet_type', as: :set_pet_type
	patch '/edit_pet_type', to: 'profiles#edit_pet_type', as: :edit_pet_type
	get '/change_profile', to: 'profiles#change_profile', as: :change_profile
	
	########################## POSTS CONTROLLER ############################
  resources :posts, except: [:new, :index]
	get '/home', to: 'posts#home', as: :home
	get '/post_settings_modal', to: 'posts#open_post_settings_modal', as: :post_settings_modal
	get '/vote', to: 'posts#vote', as: :vote
	get '/post_modal', to: 'posts#post_modal', as: :post_modal


	######################### COMMENTS CONTROLLER ###########################

	post '/comments', to: 'comments#create', as: :comments
	delete '/comments', to: 'comments#destroy', as: :destroy_comment
	get '/get_comments', to: 'comments#get_comments', as: :get_comments
	get '/get_modal_comments', to: 'comments#get_modal_comments', as: :get_modal_comments
	post '/modal_comments', to: 'comments#create_modal_comment', as: :modal_comments

	######################## RELATIONSHIPS CONTROLLER ##########################
	
	post '/follow', to: 'relationships#create', as: :follow
	get '/unfollow', to: 'relationships#destroy', as: :unfollow
	get '/following_modal', to: 'relationships#following_modal', as: :following_modal
	get 'followers_modal', to: 'relationships#followers_modal', as: :followers_modal


	# sets root to signup page if not signed in or home page if signed in.
	devise_scope :user do
		authenticated :user do
			root 'posts#home'
		end

		unauthenticated do
			root 'devise/registrations#new'
		end
	end
end

app/models/profile.rb
class Profile < ApplicationRecord
	mount_uploader :profile_image, ImageUploader
	has_many :posts, dependent: :destroy
	has_many :active_relationships, class_name: "Relationship",
																	foreign_key: "follower_id",
																	dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
																	foreign_key: "followed_id",
																	dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower
	has_many :notifications, dependent: :destroy

	belongs_to :user
	acts_as_voter
	# This is for the email_field for the form in profiles#edit view.
	attr_accessor :email

	validates :username, presence: true, length: { maximum: 20 },
												uniqueness: true
	validates :bio, length: { maximum: 150 }
	validates :animal, length: { maximum: 25 }
	validates :name, length: {maximum: 25 }
	validate :profile_image_size

	
	# Follows a user
	def follow(other_user)
		self.following << other_user
	end

	# Unfollows a user
	def unfollow(other_user)
		self.following.delete(other_user)
	end

	# Returns true if the current user is following the other user.
	def following?(other_user)
		self.following.include?(other_user)
	end

	def unread_notifications?
		self.notifications.each do |n|
			if n.read == false
				return true
			end
		end
		return false
	end

	# Defines a feed
	def feed
		following_ids = "SELECT followed_id FROM relationships
											WHERE follower_id = :profile_id"
		Post.where("profile_id IN (#{following_ids}) 
							OR profile_id = :profile_id", profile_id: self.id)
	end

	def suggestions
		follower_ids = "SELECT follower_id FROM relationships
										WHERE followed_id = :id"
		following_ids = "SELECT followed_id FROM relationships
										WHERE follower_id = :id"
		sql = "SELECT followed_id AS profile_id
					FROM relationships 
					GROUP BY followed_id
					ORDER BY COUNT(follower_id) DESC
					LIMIT 20"
		other_profiles = "SELECT id
											FROM profiles"

		popular = Profile.where("(id IN (#{sql}) AND NOT id = :id AND NOT id IN (#{following_ids})) OR (id IN (#{follower_ids}) AND id NOT IN (#{following_ids}) OR (id IN (#{other_profiles}) AND NOT id IN (#{following_ids}) AND NOT id = :id))", id: self.id).limit(30)

		
		#popular << Profile.where("profile_id IN #{follower_ids} AND profile_id NOT IN #{following_ids}")
		return popular
	end

	def search(pattern)
=begin
 _following_ids = "SELECT followed_id FROM relationships
											WHERE follower_id = :profile_id"

		
		_suggestions = "id FROM profiles 
		 WHERE username LIKE '#{pattern}'
		LIMIT 30"
AND
		 profile_id IN (#{following_ids})
		 UNION
		 SELECT profile_id FROM profiles
		 WHERE username LIKE '#{pattern}'
		 LIMIT 30"
=end
		result = Profile.where("username LIKE :pattern OR name LIKE :pattern", pattern: pattern).limit(30)
	
		return result	
	end

	# Validates the size of an uploaded picture.
		def profile_image_size
			if profile_image.size > 5.megabytes
				errors.add(:profile_image, "should be less than 5MB")
			end
		end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
include ApplicationHelper
include ProfilesHelper
	before_action :logged_in_user
	before_action :find_profile, only: [:show, :edit, :update, :welcome, 
																			:change_profile]
	before_action :correct_profile, only: [:edit, :update, :welcome]
	before_action :get_current_profile, only: [:update_profile_image, 
																							:set_pet_type, :edit_pet_type ]
	before_action :owns_profile, only: [:destroy]

	def show
	end

	def edit
		@profile.email = @profile.user.email
	end

	def update_profile_image
		if @profile.update_attributes(profile_image_update_params)
			# Handle a successful update
			flash[:success] = "Profile image updated"
		else
			#redirect_to edit_profile_path(@profile.id)
			flash[:error] = "profile image did not update"
		end

		if params[:path] == 'show'
			redirect_to @profile
		elsif params[:path] == 'edit' 
			redirect_to edit_profile_path(@profile.id)
		elsif params[:path] == 'welcome'
			redirect_to set_pet_type_path
		elsif params[:path] == 'welcome/default'
			@profile.update_attributes(:profile_image => File.open(File.join(Rails.root, "/public/#{params[:profile][:profile_image]}")))
			redirect_to set_pet_type_path
		end

	end

	def set_pet_type
		if @profile.profile_image.profile.url.nil?
			num = rand(115) + 1
			default_image = File.open(File.join(Rails.root, "/public/profile_icons/#{num}.png"))

			@profile.update_attributes(:profile_image => default_image)
		end
	end

	def edit_pet_type
		if @profile.update_attributes(profile_pet_type_params)
			# Handle a successful update
			flash[:success] = "Profile updated"
			redirect_to discover_path
		else
			flash[:danger] = "profile update did not work"
			render 'set_pet_type'
		end
	end

	def update
		@user = @profile.user
		@profile.email = params[:profile][:email]
		if @profile.update_attributes(profile_update_params) && @user.update_attributes(email: @profile.email)
			# Handle a successful update
			flash[:success] = "Profile update"
			redirect_to @profile
		else
			render 'edit'
		end
	end

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_create_params)
		@profile.user_id = current_user.id
		if @profile.save
			current_user.username = @profile.username
			flash[:success] = "New pet profile created!"
			redirect_to user_path(current_user)
		else
			render 'new'
		end
	end

	def destroy
		@user = current_user
		if @user.profiles.size == 1
			@user.profiles.first.destroy
			sign_out
			@user.destroy
			redirect_to new_user_registration_path
		else
			if current_user.username = @profile.username
				current_user.profiles.each do |p|
					if current_user.username != p.username
						current_user.update_attributes(:username => p.username)
						break
					end
				end
			end
			@profile.destroy
			redirect_to user_path(current_user)
		end
	end

	def autocomplete
		respond_to do |format|
			format.json {
				@suggestions = current_profile.search("%#{params[:query]}%")
				render json: {suggestions: @suggestions }
			}
		end
	end

	def discover
		@suggestions = current_profile.suggestions
		@popular = Post.order(cached_votes_score: :desc)
	end
	
	def read_notifications
		if current_profile.notifications.count > 0
			current_profile.notifications.each do |n|
				n.read = true
				n.save
			end
		end
	end

	def welcome

	end

	def change_profile
		current_user.update_attributes(:username => @profile.username)
		redirect_to @profile
	end

	private
		
		def profile_update_params
			params.require(:profile).permit(:username, :name, :bio, :animal)
		end

		def profile_image_update_params
			params.require(:profile).permit(:profile_image)
		end

		def profile_create_params
			params.require(:profile).permit(:username, :name, :animal)
		end

		def profile_pet_type_params
			params.require(:profile).permit(:name, :animal)
		end

		# Confirms the correct user
		def correct_profile
			# this allows user to update any profile that belongs to him only
			redirect_to(root_url) unless @profile == current_profile
		end

		def owns_profile
			redirect_to(root_url) unless current_user.profiles.include? @profile
		end
		
		def get_current_profile
			@profile = current_profile
		end

		def find_profile
			@profile = Profile.find(params[:id])
		end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
	def set_edit_profile_class
		((controller_name == "profiles") && (action_name == "update" || action_name == "edit")) ? "active-effect-4" : "non-active-effect-4" 

	end

	def set_edit_password_class
		((devise_controller?) && (action_name == "update" || action_name == "edit")) ? "active-effect-4" : "non-active-effect-4" 

	end

	def set_add_profile_class
		((controller_name == "profiles") && (action_name == "new" || action_name == "create")) ? "active-effect-4" : "non-active-effect-4" 
	end

	def set_profiles_class
		((controller_name == "users") && (action_name == "show")) ? "active-effect-4" : "non-active-effect-4" 
	end

	def current_profile
		Profile.find_by(username: current_user.username)
	end

end

app/views/profiles/discover2.html.erb
<div class="discover-body">
	<div class="container">
		<% if @suggestions %>
			<div class="explore" style="margin-top: 10%;">
				<h1>Discover People</h1>
			</div>

			<div class="carousel slide" data-type="multi" id="myCarousel">
				<div class = "frame">
					<div class="carousel-inner">
						<div class="item active">
  						<div class="center-card first-card">
								<div class="profile-card">
									<p class="profile-card-username"><%=link_to @suggestions.first.username, profile_path(@suggestions.first.id)%></p>
									<a href="<%=profile_path(@suggestions.first.id) %>">
									<div class="image">
										<div class="circle-1"></div>
										
										<div class="circle-2"></div>
										<a href="<%=profile_path(@suggestions.first.id) %>">
										<% if @suggestions.first.profile_image.profile.url.nil? %>
											<img src="/default-dog.png" width="70" height="70" alt="Jessica Potter">
										<% else %>
											<img src="<%=@suggestions.first.profile_image.profile_post2.url%>" width="70" height="70" alt="Jessica Potter">
										<% end %>
									</div>
									</a>				
					
									<div class="card-name"><%=@suggestions.first.name %></div>
									<div class="card-animal"><%=@suggestions.first.animal%></div>
			
									<div class="card-actions card-actions-<%=@suggestions.first.id%>">
										<% if current_profile.following?(@suggestions.first) %>
											<button class="card-btn unfollow-btn following-btn-<%=@suggestions.first.id%>" id= "following-btn-<%=@suggestions.first.id%>">Unfollow</button>
										<% else %>
											<button class="card-btn follow-btn follow-btn-<%=@suggestions.first.id%>" id= "follow-btn-<%=@suggestions.first.id%>">Follow</button>
	
										<% end %>
									</div>
								</div>
		
								<div class="card-stats">
										<div class="card-box" style="cursor: default;">	
											<span class="card-value"><%=@suggestions.first.posts.count%></span>
											<span class="card-parameter">Posts</span>
										</div>
									<% if @suggestions.first.followers.count == 0 %>
										<div class="card-box" style="cursor: default;"id="followers-<%=@suggestions.first.id%>">

									<% else %>
										<div class="card-box followers-modal-toggle" id="followers-<%=@suggestions.first.id%>">
									<% end %>
										<span class="card-value"><%=@suggestions.first.followers.count%></span>
										<span class="card-parameter">Followers</span>
									</div>
									
									<% if @suggestions.first.following.count == 0 %>
										<div class="card-box" style="cursor: default;" id="following-<%=@suggestions.first.id%>">
									<% else %>
										<div class="card-box following-modal-toggle" id="following-<%=@suggestions.first.id%>">
									<% end %>
										<span class="card-value"><%=@suggestions.first.following.count%></span>
										<span class="card-parameter">Following</span>
									</div>
								</div>
  						</div>
						</div>
					<% @suggestions[1..@suggestions.count].each do |profile| %>
						<div class="item">		
  						<div class="center-card second-card">
    
								<div class="profile-card">
									<p class="profile-card-username"><%=link_to profile.username, profile_path(profile.id)%></p>

									<a href="<%=profile_path(profile.id)%>">
									<div class="image">
										<div class="circle-1"></div>
										<div class="circle-2"></div>
										<% if !profile.profile_image.profile.url.nil? %>
											<img src="<%=profile.profile_image.profile_post2.url%>" width="70" height="70" alt="<%=profile.username%>">
										<% else %>
											<img src="/default-dog.png" width="70" height="70" alt="<%=profile.username%>">
										<% end %>
									</div>
									</a>			

									<div class="card-name"><%=profile.name%></div>
									<div class="card-animal"><%=profile.animal%></div>
			
									<div class="card-actions card-actions-<%=profile.id%>">
										<% if current_profile.following?(profile) %>
											<button class="card-btn unfollow-btn following-btn-<%=profile.id%>" id= "following-btn-<%=profile.id%>">Unfollow</button>
											<%# button_to "Unfollow", unfollow_path( :followed => profile.id ), :method => :delete, :class => "card-btn unfollow-btn", :id => "following-btn-#{profile.id}", :remote => true %>
										<% else %>
											<%# button_to "Follow", follow_path( :followed => profile.id ), :method => :post, :class => "card-btn follow-btn" :id => "follow-btn-#{profile.id}", :remote => true %>
											<button class="card-btn follow-btn follow-btn-<%=profile.id%>" id= "follow-btn-<%=profile.id%>">Follow</button>
										<% end %>
									</div>
								</div>
		
								<div class="card-stats">
									<div class="card-box" style="cursor: default;">
										<span class="card-value"><%=profile.posts.count%></span>
										<span class="card-parameter">Posts</span>
									</div>
									
									<% if profile.followers.count == 0 %>
										<div class="card-box" style="cursor: default;" id="followers-<%=profile.id%>">
									<% else %>
										<div class="card-box followers-modal-toggle" id="followers-<%=profile.id%>">
									<% end %>
										<span class="card-value"><%=profile.followers.count%></span>
										<span class="card-parameter">Followers</span>
									</div>
									
									<% if profile.following.count == 0 %>
										<div class="card-box" style="cursor: default;" id="following-<%=profile.id%>">
									<% else %>
										<div class="card-box following-modal-toggle" id="following-<%=profile.id%>">
									<% end %>
										<span class="card-value"><%=profile.following.count%></span>
										<span class="card-parameter">Following</span>
									</div>
								</div>
  						</div>
						</div>
					<% end %>
<!--
				<div class="item">
					<div class="center-card third-card">
    
						<div class="profile-card">
							
							<div class="image">
								<div class="circle-1"></div>
								<div class="circle-2"></div>
								<img src="http://100dayscss.com/codepen/jessica-potter.jpg" width="70" height="70" alt="Jessica Potter">
							</div>
			
							<div class="card-name">Jessica Potter</div>
							<div class="card-animal">Visual Artist</div>
			
							<div class="card-actions">
								<button class="card-btn">Follow</button>
								
							</div>
						</div>
		
						<div class="card-stats">
							<div class="card-box">
								<span class="card-value">523</span>
								<span class="card-parameter">Posts</span>
							</div>
							<div class="card-box">
								<span class="card-value">1387</span>
								<span class="card-parameter">Followers</span>
							</div>
							<div class="card-box">
								<span class="card-value">146</span>
								<span class="card-parameter">Following</span>
							</div>
						</div>
					</div>
  			</div>
		-->		
				</div>
				<a href="#myCarousel" class="carousel-control left" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left"></span>
				</a>
				<a href="#myCarousel" class="carousel-control right" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right"></span>
				</a>
			</div>
		</div>
	<% end %>

<div class="explore">
	<h1>Explore</h1>
</div>

	<div class="row" style="margin-top: 5%;">
		<% @popular.each do |post| %>
			<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
				<a>
					<div class="profile-post-container" id="post-container-<%=post.id%>">
						<%= image_tag post.image.profile_post.url, class: "profile-post-img img-responsive" %>
						<div class="img-hover-buttons">
								<p>	<%=image_tag "/dog-pawprint-on-a-heart3.png", class: "img-hover-heart"%> <span class="img-hover-likes">&nbsp;<%=post.get_upvotes.size%></span>
							&nbsp;<span class="img-hover-comment glyphicon glyphicon-comment"></span>&nbsp;<span class="img-hover-comments"><%=post.comments.count%></span>
						</p>
				
						</div>
					</div>
				</a>
			</div>
		<% end %>
	</div>
</div>
</div>

app/views/profiles/edit.html.erb
<div class="limiter profile-edit-page">
	<div class="container-login100">
		<div class="wrap-login100 main-form-container">
			<%= render 'shared/edit_account_header' %>	
			<div class="profile-card" style="float: none; height: auto; margin: auto;">
			<div class="image">
					<% if !@profile.profile_image.profile.url.nil? %>
						<div class="profile-thumbnail" style="background-image: url('<%=@profile.profile_image.profile_post2.url%>')">
					<% else %>
						<div class="profile-thumbnail" style="background-image: url('/default-dog.png')">
					<% end %>
						<span class="glyphicon glyphicon-camera">
						</span>
					</div>
					<div class="circle-1">
					</div>

					<% if current_profile == @profile %>
						<%= form_for @profile, :url => update_profile_image_path(:path => 'edit'), html: { multipart: true, class: "profile-img-edit" } do |f| %>
							<label style="cursor: pointer;">
								<div class="circle-2"></div>
								<%=f.file_field :profile_image, class: "profile-img-file", accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
							</label>
						<% end %>
					<% else %>
						<div class="circle-2"></div>
					<% end %>
				</div>
				<div class="card-name"><%=current_profile.username%></div>

				</div>


			<%= form_for(@profile, :url => edit_profile_path, html: { class: 'login100-form validate-form', novalidate: true }) do |f| %>
				
				<%= render 'shared/error_messages' %>
	

				<div class="field wrap-input100 validate-input m-b-26">
    			<span class="label-input100" style="font-size: 12px; width:90px;">Username</span>
    			<%= f.text_field :username, class: "input100", autocomplete: "username", placeholder: "Enter username" %>
					<span class="focus-input100"></span>
  			</div>

  			<div class="field wrap-input100 validate-input m-b-26">
    			<%# f.label :email %>
					<span class="label-input100" style="font-size: 12px; width:90px;">Name</span>
    			<%= f.text_field :name, class: "input100", autocomplete: "name", placeholder: "Enter Pet name" %>
					<span class="focus-input100"></span>
  			</div>

				<div class="field wrap-input100 validate-input m-b-26">
    			<%# f.label :email %>
					<span class="label-input100" style="font-size: 12px; width:90px;">Animal</span>
    			<%= f.text_field :animal, class: "input100", autocomplete: "animal", placeholder: "Enter animal type" %>
					<span class="focus-input100"></span>
  			</div>

				<div class="field wrap-input100 validate-input m-b-26">
    			<%# f.label :email %>
					<span class="label-input100" style="font-size: 12px; width:90px;">Bio</span>
    			<%= f.text_area :bio, class: "input100", autocomplete: "bio" %>
					<span class="focus-input100"></span>
  			</div>

				<div class="field wrap-input100 validate-input m-b-26">
    			<%# f.label :email %>
					<span class="label-input100" style="font-size: 12px; width:90px;">Email</span>
    			<%= f.text_field :email, class: "input100", autocomplete: "email", placeholder: "Enter email" %>
					<span class="focus-input100"></span>
  			</div>

				<div class="actions container-login100-form-btn">
  				<%= f.submit "Submit", class: "login100-form-btn" %>
  			</div>

				<div id="signup-login-div">
					<span id="signup-login-span">Unhappy? <%= link_to "Cancel my account", registration_path(@profile.user), data: { confirm: "Are you sure?" }, method: :delete, id: "signup-login-link" %></span>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/profiles/pet_type.html.erb
<div class="limiter">
	<div class="container-login100 welcome-page">
		<div class="wrap-login100">
			<div class="login100-form-title" style="background-image: url(/welcome3.png);">
				<span class="login100-form-title-1">
					
				</span>
			</div>


			<%= render 'shared/error_messages' %>
			<%= form_for(@profile, :url => edit_pet_path, html: { class: 'login100-form validate-form', novalidate: true }) do |f| %>
				
	
				<div class="field wrap-input100 validate-input m-b-26">
    			<span class="label-input100" style="font-size: 12px; width:90px;"></span>
    			<%= f.text_field :name, class: "input100", autocomplete: "Name", placeholder: "Enter name" %>
					<span class="focus-input100"></span>
  			</div>

  			<div class="field wrap-input100 validate-input m-b-26">
    			<%# f.label :email %>
					<span class="label-input100" style="font-size: 12px; width:90px;">What kind of Pet is it?</span>
    			<%= f.text_field :animal, class: "input100", autocomplete: "animal", placeholder: "Enter Pet type" %>
					<span class="focus-input100"></span>
  			</div>

				
				<div class="actions container-login100-form-btn">
  				<%= f.submit "Submit", class: "login100-form-btn" %>
  			</div>

			<% end %>


		</div>
	</div>
</div>	

app/views/profiles/read_notifications.js.erb
$('.navbar .glyphicon-asterisk').remove();
$('.notifications-item').removeClass('default-background-color');

app/views/profiles/show.html.erb
<div id="profile-body">
<div class="container">
	<div class="frame" style="margin-bottom: 100px;">
		<div class="center-card first-card">
			<div class="profile-card">
				<p class="profile-card-username"><%=@profile.username%></p>
				<div class="image">
					<% if !@profile.profile_image.profile.url.nil? %>
						<div class="profile-thumbnail" style="background-image: url('<%=@profile.profile_image.profile.url%>')">
					<% else %>
						<div class="profile-thumbnail" style="background-image: url('/default-dog.png')">
					<% end %>
						<span class="glyphicon glyphicon-camera">
						</span>
					</div>
					<div class="circle-1">
					</div>

					<% if current_profile == @profile %>
						<%= form_for @profile, :url => update_profile_image_path(:path => 'show'), html: { multipart: true, class: "profile-img-edit" } do |f| %>
							<label style="cursor: pointer;">
								<div class="circle-2"></div>
								<%=f.file_field :profile_image, class: "profile-img-file", accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
							</label>
						<% end %>
					<% else %>
						<div class="circle-2"></div>
					<% end %>
				</div>

				<div class="card-name"><%=@profile.name%></div>
				<div class="card-animal"><%=@profile.animal%></div>
				<span class="card-animal card-bio" style="position: relative; padding-top: 10px; margin-top: 10px;"><%=@profile.bio%></span>

				<% if current_profile == @profile %>
					<div class="card-actions">
						<%= button_to "Edit Profile", edit_profile_path(@profile), :method => "get", class: "card-btn" %>
					</div>
				<% else %>
					<div class="card-actions card-actions-<%=@profile.id%>">
						<% if current_profile.following?(@profile) %>
											<button class="card-btn unfollow-btn following-btn-<%=@profile.id%>" id= "following-btn-<%=@profile.id%>">Unfollow</button>
											<%# button_to "Unfollow", unfollow_path( :followed => profile.id ), :method => :delete, :class => "card-btn unfollow-btn", :id => "following-btn-#{profile.id}", :remote => true %>
										<% else %>
											<%# button_to "Follow", follow_path( :followed => profile.id ), :method => :post, :class => "card-btn follow-btn" :id => "follow-btn-#{profile.id}", :remote => true %>
											<button class="card-btn follow-btn follow-btn-<%=@profile.id%>" id= "follow-btn-<%=@profile.id%>">Follow</button>
										<% end %>

					</div>
				<% end %>
			</div>
		
			<div class="card-stats">
				<div class="card-box card-box-posts">
					<span class="card-value"><%=@profile.posts.count%></span>
					<span class="card-parameter">Posts</span>
				</div>
				
				<% if @profile.followers.count == 0 %>
					<div class="card-box" style="cursor: default;" id="followers-<%=@profile.id%>">
				<% else %>
					<div class="card-box followers-modal-toggle" id="followers-<%=@profile.id%>">
				<% end %>
					<span class="card-value"><%=@profile.followers.count%></span>
					<span class="card-parameter">Followers</span>
				</div>

				
				<% if @profile.following.count == 0 %>
					<div class="card-box" style="cursor: default;" id="following-<%=@profile.id%>">
				<% else %>
					<div class="card-box following-modal-toggle" id="following-<%=@profile.id%>">
				<% end %>
					<span class="card-value"><%=@profile.following.count%></span>
					<span class="card-parameter">Following</span>
				</div>
			</div>
  	</div><br>
		<a href="<%=destroy_user_session_path%>" data-method="delete"> <button type="button" class="btn btn-default btn-cirlce" title="Log out"><i class="glyphicon glyphicon-log-out"></i></button></a>
	</div>

<div class="row profile-posts-gallery">
	<% @profile.posts.order(created_at: :desc).each do |post| %>
		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<a>
				<div class="profile-post-container" id="post-container-<%=post.id%>">
				<%= image_tag post.image.profile_post.url, class: "profile-post-img img-responsive" %>
				<div class="img-hover-buttons">
						<p>	<%=image_tag "/dog-pawprint-on-a-heart3.png", class: "img-hover-heart"%> <span class="img-hover-likes">&nbsp;<%=post.get_upvotes.size%></span>
							&nbsp;<span class="img-hover-comment glyphicon glyphicon-comment"></span>&nbsp;<span class="img-hover-comments"><%=post.comments.count%></span>
						</p>
			
				</div>
				</div>
			</a>
		</div>
	<% end %>
</div>
</div>
</div>