config/routes.rb
Rails.application.routes.draw do
	

	###################### DEVISE CONTROLLERS ##############################
	
	devise_for :users, skip: [:sessions, :registrations]
	devise_scope :user do
		get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
		post 'sign_in', to: 'devise/sessions#create', as: :user_session
  	delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
		get 'cancel_registration', to: 'registrations#cancel', as: :cancel_user_registration
		get 'sign_up', to: 'registrations#new', as: :new_user_registration
		get 'change_password/:id', to: 'registrations#edit', as: :edit_user_registration
		patch '/change_password/:id', to: 'registrations#update', as: :update_edit_user_registration
		put '/user_registration', to: 'registrations#update'
		delete '/user_registration', to: 'registrations#destroy'
		post '/user_registration', to: 'registrations#create'
	end

	##################### USERS CONTROLLER ##############################

	resources :users, only: [:show]
	get '/delete_profiles', to: 'users#delete', as: :delete_profiles


	####################### PROFILES CONTROLLER ############################

	resources :profiles, only: [:show, :edit, :new, :destroy] do 
		member do
			patch 'edit', action: :update, :as => :update_edit
		end
	end
	post '/profiles/new', to: 'profiles#create', as: :update_new_profile
	get '/autocomplete', to: 'profiles#autocomplete', as: :autocomplete
	get '/discover', to: 'profiles#discover', as: :discover
	patch '/update_profile_img', to: 'profiles#update_profile_image', as: :update_profile_image
	get '/read_notifications', to: 'profiles#read_notifications', as: :read_notifications
	get '/welcome/:id', to: 'profiles#welcome', as: :welcome
	get '/set_pet_type', to: 'profiles#set_pet_type', as: :set_pet_type
	patch '/edit_pet_type', to: 'profiles#edit_pet_type', as: :edit_pet_type
	get '/change_profile', to: 'profiles#change_profile', as: :change_profile
	
	########################## POSTS CONTROLLER ############################
  resources :posts, except: [:new, :index]
	get '/home', to: 'posts#home', as: :home
	get '/post_settings_modal', to: 'posts#open_post_settings_modal', as: :post_settings_modal
	get '/vote', to: 'posts#vote', as: :vote
	get '/post_modal', to: 'posts#post_modal', as: :post_modal


	######################### COMMENTS CONTROLLER ###########################

	post '/comments', to: 'comments#create', as: :comments
	delete '/comments', to: 'comments#destroy', as: :destroy_comment
	get '/get_comments', to: 'comments#get_comments', as: :get_comments
	get '/get_modal_comments', to: 'comments#get_modal_comments', as: :get_modal_comments
	post '/modal_comments', to: 'comments#create_modal_comment', as: :modal_comments

	######################## RELATIONSHIPS CONTROLLER ##########################
	
	post '/follow', to: 'relationships#create', as: :follow
	get '/unfollow', to: 'relationships#destroy', as: :unfollow
	get '/following_modal', to: 'relationships#following_modal', as: :following_modal
	get 'followers_modal', to: 'relationships#followers_modal', as: :followers_modal


	# sets root to signup page if not signed in or home page if signed in.
	devise_scope :user do
		authenticated :user do
			root 'posts#home'
		end

		unauthenticated do
			root 'devise/registrations#new'
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :profiles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	before_save { self.email = email.downcase }
	validates :username, presence: true, length: { maximum: 20 },
												uniqueness: true

	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, length: { maximum: 255 }
=begin
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
=end

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include ApplicationHelper
	before_action :logged_in_user, only: [:show, :delete]
	before_action :correct_user, only: [:show]

	def show
		@user = current_user
	end
	
	def delete
		@user = current_user
	end

	private

				
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/delete.html.erb
<div class="limiter profile-selection-page">
	<div class="container-login100">
		<div class="wrap-login100 main-form-container">
			<%# render 'shared/edit_account_header' %>
			<div class="login100-form-title" style="background-image: url(/bg-09.jpg);">
				<span class="login100-form-title-1">
					Select Profile to Delete
				</span>
			</div>

			<div class="profiles-gate-container">		

				<% @user.profiles.each do |profile| %>
					<a class="profile-link" href=<%= profile_path(profile) %> data-method="delete", data-confirm="Are you sure?">
						<div class="col-md-3 col-lg-3 col-sm-3 col-xs-4 profile-btn-container"> 
							<div class="profile-img-container">
								<% if profile.profile_image.profile.url %>
								<img src="<%=profile.profile_image.profile_post2.url%>">
								<% else %>
									<img src="/profile_icons/28.png">
								<% end %>
							</div>
							<p><%=profile.username%></p>
						</div>							
					</a>

				<% end %>






<!--
					<ul class="choose-profile">
						<%# @user.profiles.each do |profile| %>
							<li class="profile">
								<div id="hover-wrapper">
									<a class="profile-link" href=<%# profile_path(profile) %> data-method="delete", data-confirm="Are you sure?">
							
											<div class="profile-icon" style="background-image:url(https://assets.nflxext.com/ffe/profiles/avatars_v2/320x320/PICON_025.png);"></div>
										<!
										<span class="profile-name"><%#profile.username%></span>
									</a>
								</div>
							</li>
						<%# end %>
					</ul>-->
				<form style="clear: both;" action=<%=user_path(current_user)%> method="get">
					<input type="submit" name="commit" value="Go back" class="login100-form-btn">
				</form>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="limiter profile-selection-page">
	<div class="container-login100">
		<div class="wrap-login100 main-form-container">
			<%= render 'shared/edit_account_header' %>
			<div class="profiles-gate-container">
				
					<span class="login100-form-title-1" id="select-profile-label">
					Select Profile
				</span>

						<% @user.profiles.each do |profile| %>
							<div class="col-md-3 col-lg-3 col-sm-3 col-xs-4 profile-btn-container"> 
								<a class="profile-link" href="<%=change_profile_path(:id => profile.id)%>">

								<div class="profile-img-container">
									<% if profile.profile_image.profile.url %>
									<img src="<%=profile.profile_image.profile_post2.url%>">
									<% else %>
										<img src="/profile_icons/28.png">
									<% end %>
								</div>
								</a>
								<p><%=profile.username%></p>
							</div>
						<% end %>


						<div class="col-md-3 col-lg-3 col-sm-3 col-xs-4 profile-btn-container"> 
							<a class="profile-link" href="<%=new_profile_path%>">

								<div class="profile-img-container">
									<img class = "add-profile-icon" src="/add-profile-icon.svg">
								</div>
							</a>
							<p>Add Profile</p>
						</div>







						<!--<span class="login100-form-btn">
						<a href=<%#user_path(current_user)%>>Go back</a
					</span>-->
					<form style="clear: both;"action=<%=delete_profiles_path%> method="get">
					<input type="submit" name="commit" value="Manage Profiles" class="login100-form-btn">
				</form>
			</div>
		</div>
	</div>
</div>