config/routes.rb
Rails.application.routes.draw do
	

	###################### DEVISE CONTROLLERS ##############################
	
	devise_for :users, skip: [:sessions, :registrations]
	devise_scope :user do
		get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
		post 'sign_in', to: 'devise/sessions#create', as: :user_session
  	delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
		get 'cancel_registration', to: 'registrations#cancel', as: :cancel_user_registration
		get 'sign_up', to: 'registrations#new', as: :new_user_registration
		get 'change_password/:id', to: 'registrations#edit', as: :edit_user_registration
		patch '/change_password/:id', to: 'registrations#update', as: :update_edit_user_registration
		put '/user_registration', to: 'registrations#update'
		delete '/user_registration', to: 'registrations#destroy'
		post '/user_registration', to: 'registrations#create'
	end

	##################### USERS CONTROLLER ##############################

	resources :users, only: [:show]
	get '/delete_profiles', to: 'users#delete', as: :delete_profiles


	####################### PROFILES CONTROLLER ############################

	resources :profiles, only: [:show, :edit, :new, :destroy] do 
		member do
			patch 'edit', action: :update, :as => :update_edit
		end
	end
	post '/profiles/new', to: 'profiles#create', as: :update_new_profile
	get '/autocomplete', to: 'profiles#autocomplete', as: :autocomplete
	get '/discover', to: 'profiles#discover', as: :discover
	patch '/update_profile_img', to: 'profiles#update_profile_image', as: :update_profile_image
	get '/read_notifications', to: 'profiles#read_notifications', as: :read_notifications
	get '/welcome/:id', to: 'profiles#welcome', as: :welcome
	get '/set_pet_type', to: 'profiles#set_pet_type', as: :set_pet_type
	patch '/edit_pet_type', to: 'profiles#edit_pet_type', as: :edit_pet_type
	get '/change_profile', to: 'profiles#change_profile', as: :change_profile
	
	########################## POSTS CONTROLLER ############################
  resources :posts, except: [:new, :index]
	get '/home', to: 'posts#home', as: :home
	get '/post_settings_modal', to: 'posts#open_post_settings_modal', as: :post_settings_modal
	get '/vote', to: 'posts#vote', as: :vote
	get '/post_modal', to: 'posts#post_modal', as: :post_modal


	######################### COMMENTS CONTROLLER ###########################

	post '/comments', to: 'comments#create', as: :comments
	delete '/comments', to: 'comments#destroy', as: :destroy_comment
	get '/get_comments', to: 'comments#get_comments', as: :get_comments
	get '/get_modal_comments', to: 'comments#get_modal_comments', as: :get_modal_comments
	post '/modal_comments', to: 'comments#create_modal_comment', as: :modal_comments

	######################## RELATIONSHIPS CONTROLLER ##########################
	
	post '/follow', to: 'relationships#create', as: :follow
	get '/unfollow', to: 'relationships#destroy', as: :unfollow
	get '/following_modal', to: 'relationships#following_modal', as: :following_modal
	get 'followers_modal', to: 'relationships#followers_modal', as: :followers_modal


	# sets root to signup page if not signed in or home page if signed in.
	devise_scope :user do
		authenticated :user do
			root 'posts#home'
		end

		unauthenticated do
			root 'devise/registrations#new'
		end
	end
end

app/views/shared/_edit_account_header.html.erb
<div class="login100-form-title" style="background-image: url(/bg-09.jpg);">
	<span class="login100-form-title-1" style="font-size: 15px">
		<nav class="cl-effect-4">
			<a class=<%= set_edit_profile_class %> href= <%= edit_profile_path(current_profile.id) %>>Edit Profile</a>
			<a class= <%= set_edit_password_class %> href=<%= edit_user_registration_path(current_user.id) %>>Change Password</a>
			<a class=<%=set_profiles_class%> href=<%=user_path(current_user)%>>Switch Profile</a>
			<!--<a class=<%= set_add_profile_class %> href=<%= new_profile_path %>>Add Profile</a>-->
		</nav>
	</span>
</div>

app/views/shared/_error_messages.html.erb
<% if devise_controller? || controller_name == 'users'%>
	<% model = @user %>
<% elsif controller_name == 'profiles' && (action_name == 'edit' || action_name == 'new' || action_name == 'create') || action_name == 'set_pet_type' || action_name == 'edit_pet_type' %>
	<% model = @profile %>
<% elsif controller_name == 'profiles' && action_name == 'update' %>

<!-- We also need to validate the email field -->
	<% model = @profile.errors.any? ? @profile : @user %>

<% end %>

<% if model.errors.any? %>
	<div id="error_explanation">
		<ul>
		<li>
			<%= model.errors.full_messages.first %>
		</li>
		</ul>
	</div>
<% end %>

app/views/shared/_followers_modal.html.erb
<div class="modal fade in followers-modal" id="followers-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close-btn"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
			<h4 class="modal-title"> Followers </h4>
		</div>
		<div class="modal-body notifications-body relationships-body">
			<ul>
				<% @user_profile.followers.each do |follower| %>
					<li class="profile-li">
						<div class="profile-item-container">
							<div class="profile-info-container">
								<a href="<%=profile_path(follower.id)%>"class="profile-thumb-container">
									<% if follower.profile_image.profile_post2.url %>
										<img class="profile-thumb" src="<%=follower.profile_image.profile_post2.url%>">
									<% else %>
										<img class="profile-thumb" src="/profile_default.png"></img>
									<% end %>

								</a>
								<div class="profile-information-container">
									<div class="profile-information-username">
										<a href="<%=profile_path(follower.id)%>"class="username-link"><%=follower.username%></a>
									</div>
									<div class="profile-information-name"><%=follower.name%></div>
								</div>
								
							</div>
								<% if follower != current_profile %>				
								<div class="card-actions card-actions-<%=follower.id%>" style="float: right;">
										<% if current_profile.following?(follower) %>
											<button class="card-btn unfollow-btn following-btn-<%=follower.id%>" id= "following-btn-<%=follower.id%>">Unfollow</button>
											<%# button_to "Unfollow", unfollow_path( :followed => profile.id ), :method => :delete, :class => "card-btn unfollow-btn", :id => "following-btn-#{profile.id}", :remote => true %>
										<% else %>
											<%# button_to "Follow", follow_path( :followed => profile.id ), :method => :post, :class => "card-btn follow-btn" :id => "follow-btn-#{profile.id}", :remote => true %>
											<button class="card-btn follow-btn follow-btn-<%=follower.id%>" id= "follow-btn-<%=follower.id%>">Follow</button>
										<% end %>
									</div>
								<% end %>
								

							
						</div>
					</li>
				<% end %>
			</ul>
		</div>
		</div>
	</div>
</div>

app/views/shared/_following_modal.html.erb
<div class="modal fade in following-modal" id="following-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close-btn"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>

			<h4 class="modal-title"> Following </h4>
		</div>
		<div class="modal-body notifications-body relationships-body">
			<ul>
				<% @user_profile.following.each do |following| %>
					<li class="profile-li">
						<div class="profile-item-container">
							<div class="profile-info-container">
								<a href="<%=profile_path(following.id)%>"class="profile-thumb-container">
									<% if following.profile_image.profile_post2.url %>
										<img class="profile-thumb" src="<%=following.profile_image.profile_post2.url%>">
									<% else %>
										<img class="profile-thumb" src="/profile_default.png"></img>
									<% end %>
								</a>
								<div class="profile-information-container">
									<div class="profile-information-username">
										<a href="<%=profile_path(following.id)%>"class="username-link"><%=following.username%></a>
									</div>
									<div class="profile-information-name"><%=following.name%></div>
								</div>
								
							</div>
							<% if following != current_profile %>
							<div class="card-actions card-actions-<%=following.id%>" style="float: right;">
										<% if current_profile.following?(following) %>
											<button class="card-btn unfollow-btn following-btn-<%=following.id%>" id= "following-btn-<%=following.id%>">Unfollow</button>
											<%# button_to "Unfollow", unfollow_path( :followed => profile.id ), :method => :delete, :class => "card-btn unfollow-btn", :id => "following-btn-#{profile.id}", :remote => true %>
										<% else %>
											<%# button_to "Follow", follow_path( :followed => profile.id ), :method => :post, :class => "card-btn follow-btn" :id => "follow-btn-#{profile.id}", :remote => true %>
											<button class="card-btn follow-btn follow-btn-<%=following.id%>" id= "follow-btn-<%=following.id%>">Follow</button>
										<% end %>
									</div>
								<% end %>

						</div>
					</li>
				<% end %>
			</ul>
		</div>
		</div>
	</div>
</div>

app/views/shared/_image_upload_modal.html.erb
<div class="modal fade in" id="image-upload-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"> Upload Image </h4>
			</div>
			<div class="modal-body">
				<%= form_for Post.new, html: {multipart: true, class: "login101-form"}, :remote => true do |f| %>
					<div class="field">
						<label class="file-btn">
							<span class="glyphicon glyphicon-camera"></span>
							<%= f.file_field :image, class: "img-file", accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
							</label>
					</div>
					<div class="upload-preview">
						<img class= "img-responsive100" id="cropbox"/>
					</div>

					<div class="field">
						<label>Caption</label>
						<%= f.text_area :description, placeholder: "Write a cation..." %>
					</div>

					<div class="actions">
						<%= f.submit class: "login100-form-btn login101-form-btn"  %>
					</div>
				<% end %>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/shared/_img_modal.html.erb
<div class="modal fade in img-modal" id="image-modal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class="col-md-8 modal-image">
          	<img class="clicked-img img-responsive" src="<%= @post.image.profile_post1.url %>">
						<% if @prev %>
            	<a class="img-modal-btn left" id="left-<%=@prev%>"><i class="glyphicon glyphicon-chevron-left"></i></a>
						<% end %>
						<% if @next %>
            	<a class="img-modal-btn right" id="right-<%=@next%>"><i class="glyphicon glyphicon-chevron-right"></i></a>
						<% end %>
          </div>
          <div class="col-md-4 modal-meta">
            <div class="modal-meta-top">
              <button type="button" class="close"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
              <div class="dont-break-out img-poster clearfix">
								<% if !@post.profile.profile_image.profile.url.nil? %>
                	<a href="<%=profile_path(@post.profile.id)%>"><img class="img-circle" src="<%=@post.profile.profile_image.profile_post2.url%>"/></a>
								<% else %>
									<a href="<%=profile_path(@post.profile.id)%>"><img class="img-circle" src="/default-dog.png"/></a>
								<% end %>
                <strong><a href="<%=profile_path(@post.profile.id)%>"><%=@post.profile.username%></a></strong>
                <span><%= time_ago_in_words(@post.created_at) %> ago</span><br>
								
								<div class="like-container">
									<a class="vote-call" id="like-<%=@post.id%>"href=""><%= image_tag "/dog-pawprint-on-a-heart.png", style: "float: left; margin-right: 15px;" %>
									<% if current_profile.liked? @post %>
										<div class="like-btn like-btn<%=@post.id%> liked">
									<% else %>
										<div class="like-btn like-btn<%=@post.id%>">
									<% end %>
											<img src="/dog-pawprint-on-a-heart1.png" style="width: 25px; height: auto;">
										</div>
									</a>
								</div>&nbsp;&nbsp;
								<span class="bold-text likes-count-<%=@post.id%>"> <%=@post.get_upvotes.size%> <%="like".pluralize(@post.get_upvotes.size)%></span>
								
									<span title="Post settings" class="glyphicon glyphicon-cog" id="post-settings=<%=@post.id%>" style="float: right;"></span>

								
								<p><%=@post.description.strip()%></p>

              </div>
							<% if @post.comments.size > 10 %>
									<p class="more-comments-link" id="more-comments-<%=@post.id%>" style="padding: 20px 20px 0 20px; text-align: center; font-family: Poppins-Bold; font-size: 1em; font-weight: 900;">Load more comments</p>
							<% end %>

							<ul class="dont-break-out comment-section img-comment-list img-comment-list-<%=@post.id%>">

								<% @post.comments.order(created_at: :desc)[0..9].reverse.each do |comment| %>
                	<li id="comment-<%=comment.id%>">
                  	<div class="comment-img">
                    	<% if !comment.profile.profile_image.profile.url.nil? %>
                				<a href="<%=profile_path(comment.profile.id)%>"><img src="<%=comment.profile.profile_image.profile_post2.url%>"/></a>
											<% else %>
												<a href="<%=profile_path(comment.profile.id)%>"><img src="/default-dog.png"/></a>
											<% end %>
                  	</div>
                  	<div class="comment-text">
                    	<strong><a href="<%=profile_path(comment.profile.id)%>"><%=comment.profile.username%></a></strong>
                    	<p><%=comment.content.strip()%></p> <span class="date sub-text">on <%= comment.created_at.strftime("%a, %d %b %Y, %I:%M %P") %></span>
                  	</div>

										<% if current_profile == comment.profile %>
												
												<span class="glyphicon glyphicon-remove" id="comment-delete-<%=comment.id%>"></span>
										<% end %>

                	</li>
								<% end %>
              </ul>
            </div>
            <div class="modal-meta-bottom">
							<form>
              <textarea name="content" class="comment-text-area" id="comment-text-area-<%=@post.id%>"style="border: none; height: 34px; outline: none; padding: 0; padding-top: 3%;margin-bottom: 0; font-family: inherit;" placeholder="Leave a commment.."/>
							<input type = "hidden" name="post_id" value="<%=@post.id%>">
							<input type="hidden" name="profile_id" value = "<%=current_profile.id %>">
							</form>
            </div>
          </div>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/shared/_main_nav_bar.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
		<div class="container">
    		<div class="navbar-header">	
      		<a class="navbar-brand pull-left" style="padding: 0; padding-top; 30px; padding-bottom: 5px;"href=<%=home_path%>><img src ="/pet_home2.png" style=" margin-left: 15px; padding-top: 6px; width: 40px; height: auto;"></a>
				</div>
				<div class="navbar-header pull-right">
					<div class="pull-right right-nav-buttons">
						<button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-mid-collapse">
      				<span class="sr-only">Toggle navigation</span>
        			<span class="glyphicon glyphicon-search"></span>
      			</button>
						<a id="image-upload-toggle"><button class="glyphicon glyphicon-plus"style="font-size: 20px;" data-toggle="modal" data-target="#image-upload-modal"></button></a>
      			<a href="<%=discover_path%>"><button><img src="/discover-icon.png" style="width: 20px; height: 20px;"></button></a>
						<% if current_profile.unread_notifications? %>
      				<a id="pet-heart-icon"><span class="glyphicon glyphicon-asterisk"></span><button data-toggle="modal" data-target="#notifications-modal"><img src="/pet-heart-icon2.png" style="width: 20px; height: 20px;"></button></a>
						<% else %>
							<a><button data-toggle="modal" data-target="#notifications-modal"><img src="/pet-heart-icon2.png" style="width: 20px; height: 20px;"></button></a>
						<% end %>
      		<a href=<%=profile_path(Profile.find_by(username: current_user.username)) %>><button><img src="/cat_profile_icon2.svg" style="width: 20px; height: 20px;"></button></a>
					</div>
				</div>
					<div class="navbar-collapse collapse" id="navbar-mid-collapse">
						<form class="navbar-form" role="Search" style="text-align: center;">
      				<div class="input-group ui-widget">
        				<input type="text" id="main-search" class="form-control" placeholder="Search">
        				<!--<span class="input-group-btn">
          				<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>-->
        			
      				</div>
    				</form>
					</div>	
		</div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<div class="modal fade in" id="notifications-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"> Notifications </h4>
			</div>
			<div class="modal-body notifications-body">
				<% if current_profile.notifications.count == 0 %>
					<div class="bone-heart-container">
						<img src="/bones.png" alt="heart">
						<p>You can see who liked and commented on your posts here.</p>
					</div>
				<% else %>
				<ul>
					<% current_profile.notifications.order(created_at: :desc).each do |notification| %>
						<% if notification.notification_type == "comment" %>
								<% if !notification.read %>
									<li class="notifications-item default-background-color">
								<% else %>
									<li class="notifications-item">
								<% end %>
									<div class="ac-item-container">
										<a href="<%=profile_path(notification.notified_by)%>" class="notifications-menu-item">
										<div class="small-thumb-container">
											<% if notification.notified_by.profile_image.thumb.url %>
												<img class="small-thumb" style="width: 30px; height: 30px;"src="<%=notification.notified_by.profile_image.profile_post2.url%>">
											<% else %>
												<img class="small-thumb" style="width: 30px; height: 30px;"src="/profile_default.png">
											<% end %>
										</div>&nbsp;&nbsp;
										</a>
										<a href="<%=profile_path(notification.notified_by)%>" class="notifications-menu-item">

										<span class="notifications-username"><%=notification.notified_by.username%></span></a>&nbsp; <span class="notifcations-text"> commented on your photo</span>
											<a href="<%=post_path(notification.post.id)%>" class="notifications-menu-item">

												<img style="width: 30px; height: 30px; float: right;"src=<%=notification.post.image.profile_post2.url%>>
											</a>


									</div>
								</li>
						<% elsif notification.notification_type == "like" %>
								<% if !notification.read %>
									<li class="notifications-item" style="background-color: #ebeeef;">
								<% else %>
									<li class="notifications-item">
								<% end %>
									<div class="ac-item-container">
										<a href="<%=profile_path(notification.notified_by)%>" class="notifications-menu-item">
										<div class="small-thumb-container">
											<% if notification.notified_by.profile_image.thumb.url %>
												<img class="small-thumb" style="width: 30px; height: 30px;"src="<%=notification.notified_by.profile_image.profile_post2.url%>">
											<% else %>
												<img class="small-thumb" style="width: 30px; height: 30px;"src="/profile_default.png">
											<% end %>
										</div>&nbsp;&nbsp;
										</a>
										<a href="<%=profile_path(notification.notified_by)%>" class="notifications-menu-item">
											<span class="notifications-username"><%=notification.notified_by.username%></span></a>&nbsp; <span class="notifcations-text"> liked your photo</span>
											<a href="<%=post_path(notification.post.id)%>">
												<img style="width: 30px; height: 30px; float: right;"src=<%=notification.post.image.profile_post2.url%>>
											</a>
										
									</div>
								</li>

						<% elsif notification.notification_type == "follower" %>
								<% if !notification.read %>
									<li class="notifications-item" style="background-color: #ebeeef;">
								<% else %>
									<li class="notifications-item">
								<% end %>

									<div class="ac-item-container">
										<div style="display: inline-block;">
										<a href="<%=profile_path(notification.notified_by)%>" class="notifications-menu-item">

										<div class="small-thumb-container">
											<% if notification.notified_by.profile_image.profile_post2.url %>
												<img class="small-thumb" style="width: 30px; height: 30px;"src="<%=notification.notified_by.profile_image.profile_post2.url%>">
											<% else %>
												<img class="small-thumb" style="width: 30px; height: 30px;"src="/profile_default.png">
											<% end %>
										</div>&nbsp;&nbsp;
									</a>
<!--
										<div class="item-info">
											<p class="username-item"><%#notification.notified_by.username%> started following you</p>
											<img class="small-thumb" style="width: 30px; height: 30px; float: right;"src=<%#notification.notified_by.profile_image.thumb%>>

										</div>-->
										<a href="<%=profile_path(notification.notified_by)%>" class="notifications-menu-item">
										<span class="notifications-username"><%=notification.notified_by.username%></span></a>&nbsp; <span class="notifcations-text"> started following you</span>
										</div>
									
											<div class="card-actions card-actions-<%=notification.notified_by.id%>" style="margin: 0; float: right;">
										<% if current_profile.following?(notification.notified_by) %>
											<button style="margin: 0;"class="card-btn unfollow-btn following-btn-<%=notification.notified_by.id%>" id= "following-btn-<%=notification.notified_by.id%>">Unfollow</button>
											<%# button_to "Unfollow", unfollow_path( :followed => profile.id ), :method => :delete, :class => "card-btn unfollow-btn", :id => "following-btn-#{profile.id}", :remote => true %>
										<% else %>
											<%# button_to "Follow", follow_path( :followed => profile.id ), :method => :post, :class => "card-btn follow-btn" :id => "follow-btn-#{profile.id}", :remote => true %>
											<button style="margin: 0;" class="card-btn follow-btn follow-btn-<%=notification.notified_by.id%>" id= "follow-btn-<%=notification.notified_by.id%>">Follow</button>
										<% end %>
									</div>

									</div>
								</li>

						<% end %>
					<% end %>
				</ul>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/shared/_post_settings_modal.html.erb
<div class="modal fade in post-settings-modal" id="post-settings-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-body post-settings-body">
				<ul class="post-settings-list">
					<%= link_to post_path(@current_post.id) do %>
						<li>Go to post</li>
					<% end %>
					<% if @current_post.profile == current_profile %>
						<%= link_to edit_post_path(@current_post.id) do %>
							<li>Edit post</li>
						<% end %>
						<li class="post-settings-delete" id="post-delete-<%=@current_post.id%>">Delete</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/shared/_select_profile_image_modal.html.erb
<%= javascript_include_tag "welcome" %>
<div class="modal fade in" id="select-profile-image-modal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"> Select Profile Image </h4>
			</div>
			<div class="modal-body">

				<div id="profile_images_container">
					<% 115.times do |i|%>
						<div class="col-md-1 col-lg-1 col-sm-2 col-xs-3 select_profile_image_container">
    					<img src="/profile_icons/<%=i + 1%>.png"/>
						</div>
    			<% end %>
				</div>
				<%= form_for @profile, url: update_profile_image_path(:path => 'welcome/default'), html: {class: "login101-form"} do |f| %>
					<%= f.hidden_field :profile_image, :value => "/profile_icons/5.png", id: "profile_image_input" %>
			</div>
			<div class="modal-footer">
				<div class="col-md-1 col-lg-1 col-sm-1 col-xs-1 select_profile_image_preview">
    					<img src="/profile_icons/<%=5%>.png"/>
						</div>

				<div class="actions">
					<%= f.submit "Submit", class: "login100-form-btn login101-form-btn" %>
				</div>
			<% end%>
			</div>
		</div>
	</div>
</div>