config/routes.rb
Rails.application.routes.draw do
	

	###################### DEVISE CONTROLLERS ##############################
	
	devise_for :users, skip: [:sessions, :registrations]
	devise_scope :user do
		get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
		post 'sign_in', to: 'devise/sessions#create', as: :user_session
  	delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
		get 'cancel_registration', to: 'registrations#cancel', as: :cancel_user_registration
		get 'sign_up', to: 'registrations#new', as: :new_user_registration
		get 'change_password/:id', to: 'registrations#edit', as: :edit_user_registration
		patch '/change_password/:id', to: 'registrations#update', as: :update_edit_user_registration
		put '/user_registration', to: 'registrations#update'
		delete '/user_registration', to: 'registrations#destroy'
		post '/user_registration', to: 'registrations#create'
	end

	##################### USERS CONTROLLER ##############################

	resources :users, only: [:show]
	get '/delete_profiles', to: 'users#delete', as: :delete_profiles


	####################### PROFILES CONTROLLER ############################

	resources :profiles, only: [:show, :edit, :new, :destroy] do 
		member do
			patch 'edit', action: :update, :as => :update_edit
		end
	end
	post '/profiles/new', to: 'profiles#create', as: :update_new_profile
	get '/autocomplete', to: 'profiles#autocomplete', as: :autocomplete
	get '/discover', to: 'profiles#discover', as: :discover
	patch '/update_profile_img', to: 'profiles#update_profile_image', as: :update_profile_image
	get '/read_notifications', to: 'profiles#read_notifications', as: :read_notifications
	get '/welcome/:id', to: 'profiles#welcome', as: :welcome
	get '/set_pet_type', to: 'profiles#set_pet_type', as: :set_pet_type
	patch '/edit_pet_type', to: 'profiles#edit_pet_type', as: :edit_pet_type
	get '/change_profile', to: 'profiles#change_profile', as: :change_profile
	
	########################## POSTS CONTROLLER ############################
  resources :posts, except: [:new, :index]
	get '/home', to: 'posts#home', as: :home
	get '/post_settings_modal', to: 'posts#open_post_settings_modal', as: :post_settings_modal
	get '/vote', to: 'posts#vote', as: :vote
	get '/post_modal', to: 'posts#post_modal', as: :post_modal


	######################### COMMENTS CONTROLLER ###########################

	post '/comments', to: 'comments#create', as: :comments
	delete '/comments', to: 'comments#destroy', as: :destroy_comment
	get '/get_comments', to: 'comments#get_comments', as: :get_comments
	get '/get_modal_comments', to: 'comments#get_modal_comments', as: :get_modal_comments
	post '/modal_comments', to: 'comments#create_modal_comment', as: :modal_comments

	######################## RELATIONSHIPS CONTROLLER ##########################
	
	post '/follow', to: 'relationships#create', as: :follow
	get '/unfollow', to: 'relationships#destroy', as: :unfollow
	get '/following_modal', to: 'relationships#following_modal', as: :following_modal
	get 'followers_modal', to: 'relationships#followers_modal', as: :followers_modal


	# sets root to signup page if not signed in or home page if signed in.
	devise_scope :user do
		authenticated :user do
			root 'posts#home'
		end

		unauthenticated do
			root 'devise/registrations#new'
		end
	end
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :profile
	has_many :comments, dependent: :destroy
	has_many :notifications, dependent: :destroy
	acts_as_votable

	validates :image, presence: true
	validates :description, length: { maximum: 150 }
	validate :image_size

	private

		# Validates the size of an uploaded picture.
		def image_size
			if image.size > 5.megabytes
				errors.add(:image, "should be less than 5MB")
			end
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include ApplicationHelper
	include ProfilesHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :logged_in_user
	before_action :correct_post, only: [:edit, :update, :destroy]
	protect_from_forgery :except => :vote

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
		@post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
		@post = Post.find(params[:id])
  end

	def open_post_settings_modal
		@current_post = Post.find(params[:post_id])
		respond_to do |format|
			format.js {}
		end
	end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
		@post.profile_id = current_profile.id
		respond_to do |format|
      if @post.save
        format.html { 
					flash[:success] = "New post created!"
					redirect_to profile_path(current_profile)
				}
        format.json { render :show, status: :created, location: @post }
      else
				format.js {}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      @post.update_attributes(:description => params[:post][:description])
			if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
		@post = Post.find(params[:post_id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to current_profile, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def home
		respond_to do |format|
			if signed_in?
				format.html {
					@profile = current_profile	
					@post = Post.new
					@posts = current_profile.posts.build
					@feed_items = current_profile.feed.order(created_at: :desc)[0..19]
					if @feed_items.count == 0
						redirect_to discover_path
					end
				}

				format.js {
					page = params[:page].to_i
					offset = page * 20 - 1
					@post_count = offset + 1 - 20
					@feed_items = current_profile.feed.order(created_at: :desc)[(offset - 19)..offset]
				}
			end
		end
	end

	def vote
		@post = Post.find(params[:post])
		if !current_profile.liked? @post
			@post.liked_by current_profile
			if current_profile != @post.profile
				@notification = Notification.new
				@notification.notified_by_id = current_profile.id
				@notification.profile_id = @post.profile_id
				@notification.post_id = @post.id
				@notification.notification_type = "like"
				@notification.save
			end
		elsif current_profile.liked? @post
			@post.unliked_by current_profile
			if current_profile != @post.profile
				@notification = Notification.find_by(:profile_id => @post.profile_id, :notified_by => current_user.id, :post_id => @post.id, :notification_type => "like")
				@notification.destroy
			end
		end

		respond_to do |format|
			format.js {
			}
			format.json {}
			format.html {}
		end
	end

	def post_modal
		@post = Post.find(params[:post_id])
		@prev = params[:prev] if params[:prev].to_i >= 0	
		@next = params[:next] if params[:next].to_i >= 0
		respond_to do |format|
			format.html {}

			format.js {}
		end

	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

		def correct_post
			@post = Post.find(params[:id])		
		redirect_to(root_url) unless @post.profile == current_profile

		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :post_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_more_posts.html.erb
<% post_count = @post_count %>
	<% @feed_items.each do |post| %>
		<div class="row">
			<div class="col-md-offset-2 col-lg-offset-2 col-sm-offset-2 col-xs-offset-2 col-lg-8 col-md-8 col-sm-8 col-xs-8 post-container" id="post-count-<%=post_count%>">
				<div class="thumbnail">
						<div class="modal-header">
							<a href=<%=profile_path(post.profile)%>>
								<% if !post.profile.profile_image %>
									<%= image_tag post.profile.profile_image.thumb.url %>
								<% else %>
									<%= image_tag '/profile_default.png', style: "width: 30px; height: 30px;", class:"round-thumb" %>
								<% end %>
								<span class="username-feed"><%=post.profile.username%></span>
							</a>

						</div>
						<%= image_tag post.image.profile_post1.url, class: "img-responsive feed-img"%>
					<div class="caption">
						<p>
							<a href="#"><%= image_tag "/dog-pawprint-on-a-heart.png", style: "float: left; margin-right: 15px; width: 25px; height: auto;" %></a>
							<a class="glyphicon glyphicon-comment" style="width: 32px; height: auto; cursor: pointer; font-size: 25px;"></a>
						</p>
						<span style="clear:both; padding-top: 10px;", class="bold-text"> 0 likes</span><br><br>
						<% if !post.description.blank? %>
						<p>
						<span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=post.profile.username%></span> <span class="comment-styles"><%=post.description%></span>
						</p>
						<% end %>
						<div style="clear: both"></div>
						<div class="comment-section" id="comment-section-<%=post.id%>">
							<% if post.comments.size > 5 %>
								<span style="clear:both; padding-top: 10px; padding-bottom: 10px; margin-bottom: 10px; bottom: 10px;", class="more-comments-link" id="more-comments-<%=post.id%>">Load more comments</span>
							<% end %>
						<% post.comments.order(created_at: :desc)[0..4].reverse.each do |comment| %>
							<p>
								<span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=comment.profile.username%></span> <span class="comment-styles"><%=comment.content%></span>
							</p>
						<% end %>
						</div>
							<p class="time-ago"><%= time_ago_in_words(post.created_at) %> ago</p>
							<div class="comment-form-container">
								<%= form_for Comment.new, html: { multipart: true, class: "comment-form" }, :remote => true, :authenticity_token => true do |f| %>
									<%= f.text_area :content, placeholder: "Add a comment...", class: "comment-text-area", id: "comment-text-area-#{post.id}" %>
									<%= f.hidden_field :post_id, :value => post.id %>
									<%= f.hidden_field :profile_id, :value => current_profile.id %>
								<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<% post_count = post_count + 1 %>
	<% end %>

app/views/posts/edit.html.erb
<div class="container" id="post-edit-container">
<div class="row">
	<div class="col-md-offset-2 col-lg-offset-2 col-sm-offset-2 col-lg-8 col-md-8 col-sm-8 col-xs-12 post-container">
		<div class="thumbnail">
			<div class="modal-header">
				<a href=<%=profile_path(@post.profile)%>>
					<% if !@post.profile.profile_image %>
						<%= image_tag @post.profile.profile_image.profile_post2.url %>
					<% else %>
						<%= image_tag '/profile_default.png', style: "width: 30px; height: 30px;", class:"round-thumb" %>
					<% end %>
					<span class="username-feed"><%=@post.profile.username%></span>
				</a>
			</div>
			<%= image_tag @post.image.profile_post1.url, class: "img-responsive feed-img"%>
			<div class="caption">
				<div style="clear: both"></div>
				<%= form_for(@post) do |f| %>
					<%= f.text_area :description, autofocus: true, class: "comment-text-area", id: "post-text-area-#{@post.id}" %>
				<% end %>
				
			</div>
		</div>
	</div>
</div>

app/views/posts/home.html.erb
<div class="feed-body">
<div class="container" id="feed-container">
	<% post_count = 0 %>
	<% @feed_items.each do |post| %>
		<div class="row">
			<div class="col-md-offset-2 col-lg-offset-2 col-lg-8 col-md-8 col-sm-12 col-xs-12 post-container" id="post-count-<%=post_count%>">
				<div class="thumbnail">
						<div class="modal-header">
							<a href=<%=profile_path(post.profile)%>>
								<% if !post.profile.profile_image %>
									<%= image_tag post.profile.profile_image.profile_post2.url %>
								<% else %>
									<%= image_tag '/profile_default.png', style: "width: 30px; height: 30px;", class:"round-thumb" %>
								<% end %>
								<span class="username-feed"><%=post.profile.username%></span>
								<% if current_profile == post.profile %>
								<% end %>
							</a>
							<span title="Post settings" id = "post-settings-<%=post.id%>" class="glyphicon glyphicon-cog" style="float: right;"></span>

						</div>
						<%= image_tag post.image.profile_post1.url, class: "img-responsive feed-img"%>
					<div class="caption">
						<p>
							<div class="like-container">
								<a href="<%=vote_path(:post => post)%>" data-remote="true"><%= image_tag "/dog-pawprint-on-a-heart.png", style: "float: left; margin-right: 15px;" %>
								<% if current_profile.liked? post %>
									<div class="like-btn like-btn<%=post.id%> liked">
								<% else %>
									<div class="like-btn like-btn<%=post.id%>">
								<% end %>
										<img src="/dog-pawprint-on-a-heart1.png" style="width: 25px; height: auto;">
									</div>
							</div>
							</a>
							<a class="glyphicon glyphicon-comment" style="width: 32px; height: auto; cursor: pointer; font-size: 25px;"></a>
						</p>
						<span style="clear:both; padding-top: 10px;", class="bold-text likes-count-<%=post.id%>"> <%=post.get_upvotes.size%> <%="like".pluralize(post.get_upvotes.size)%></span><br><br>
						<% if !post.description.blank? %>
						<p>
						<span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=post.profile.username%></span> <span class="comment-styles"><%=post.description%></span>
						</p>
						<% end %>
						<div style="clear: both"></div>
						<div class="comment-section" id="comment-section-<%=post.id%>">
							<% if post.comments.size > 5 %>
								<span style="clear:both; padding-top: 10px; padding-bottom: 10px; margin-bottom: 10px; bottom: 10px;", class="more-comments-link" id="more-comments-<%=post.id%>">Load more comments</span>
							<% end %>
						<% post.comments.order(created_at: :desc)[0..4].reverse.each do |comment| %>
							<p id="comment-<%=comment.id%>">
								<% if current_profile == comment.profile %>
									<a href="<%=profile_path(comment.profile.id)%>"><span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=comment.profile.username%></span></a> <span class="comment-styles"><%=comment.content%></span>

									<%= link_to destroy_comment_path(:comment_id => comment.id), style: "float: right;", :method => :delete, :data => { :confirm => "Are you sure?" }, :remote  => true do %>
										<span class="glyphicon glyphicon-remove"></span>

									<% end %>
								<% else %>
									<a href="<%=profile_path(comment.profile.id)%>"><span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=comment.profile.username%></span></a> <span class="comment-styles"><%=comment.content%></span>
								<% end %>
							</p>
						<% end %>
						</div>
							<p class="time-ago"><%= time_ago_in_words(post.created_at) %> ago</p>
							<div class="comment-form-container">
								<%= form_for Comment.new, html: { multipart: true, class: "comment-form" }, :remote => true, :authenticity_token => true do |f| %>
									<%= f.text_area :content, placeholder: "Add a comment...", class: "comment-text-area", id: "comment-text-area-#{post.id}" %>
									<%= f.hidden_field :post_id, :value => post.id %>
									<%= f.hidden_field :profile_id, :value => current_profile.id %>
								<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<% post_count = post_count + 1 %>
	<% end %>
</div>
</div>

app/views/posts/home.js.erb
<% if !@feed_items.nil? %>
	$('.container').append("<%= escape_javascript render(:partial => '/posts/more_posts', :locals => { @post_count => @post_count, @feed_items => @feed_items}) %>");
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= post.image %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/open_post_settings_modal.js.erb
$('.container').append("<%= escape_javascript render(:partial => '/shared/post_settings_modal', :locals => { @current_post => @post }) %>");
$('.page-overlay').show()

app/views/posts/post_modal.js.erb
$('.container').append("<%= escape_javascript render(:partial => '/shared/img_modal', :locals => { @post => @post, @prev => @prev, @next => @next }) %>");
$('.page-overlay').show()

app/views/posts/show.html.erb
<%# javascript_include_tag "home" %>
<%# javascript_include_tag "post_settings_modal" %>
<div class="container" id="post-show-container">
<div class="row">
	<div class="col-md-offset-2 col-lg-offset-2 col-sm-offset-2 col-lg-8 col-md-8 col-sm-8 col-xs-12 post-container">
		<div class="thumbnail">
			<div class="modal-header">
				<a href=<%=profile_path(@post.profile)%>>
					<% if !@post.profile.profile_image %>
						<%= image_tag @post.profile.profile_image.profile_post2.url %>
					<% else %>
						<%= image_tag '/profile_default.png', style: "width: 30px; height: 30px;", class:"round-thumb" %>
					<% end %>
					<span class="username-feed"><%=@post.profile.username%></span>
				</a>
				<span title="Post settings" id = "post-settings-<%=@post.id%>" class="glyphicon glyphicon-cog" style="float: right;"></span>
			</div>
			<%= image_tag @post.image.profile_post1.url, class: "img-responsive feed-img"%>
			<div class="caption">
				<p>
					<div class="like-container">
						<a href="<%=vote_path(:post => @post)%>" data-remote="true"><%= image_tag "/dog-pawprint-on-a-heart.png", style: "float: left; margin-right: 15px;" %>
							<% if current_profile.liked? @post %>
								<div class="like-btn like-btn<%=@post.id%> liked">
							<% else %>
								<div class="like-btn like-btn<%=@post.id%>">
							<% end %>
									<img src="/dog-pawprint-on-a-heart1.png" style="width: 25px; height: auto;">
								</div>
							</div>
						</a>
						<a class="glyphicon glyphicon-comment" style="width: 32px; height: auto; cursor: pointer; font-size: 25px;"></a>
				</p>
				<span style="clear:both; padding-top: 10px;", class="bold-text likes-count-<%=@post.id%>"> <%=@post.get_upvotes.size%> <%="like".pluralize(@post.get_upvotes.size)%></span><br><br>
				<% if !@post.description.blank? %>
					<p>
						<span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=@post.profile.username%></span> <span class="comment-styles"><%=@post.description%></span>
					</p>
				<% end %>
				<div style="clear: both"></div>
				<div class="comment-section" id="comment-section-<%=@post.id%>">
					<% if @post.comments.size > 5 %>
						<span style="clear:both; padding-top: 10px; padding-bottom: 10px; margin-bottom: 10px; bottom: 10px;", class="more-comments-link" id="more-comments-<%=@post.id%>">Load more comments</span>
					<% end %>
					<% @post.comments.order(created_at: :desc)[0..4].reverse.each do |comment| %>
						<p id="comment-<%=comment.id%>">
							<% if current_profile == comment.profile %>
								<a href="<%=profile_path(comment.profile.id)%>"><span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=comment.profile.username%></span></a> <span class="comment-styles"><%=comment.content%></span>

								<%= link_to destroy_comment_path(:comment_id => comment.id), style: "float: right;", :method => :delete, :data => { :confirm => "Are you sure?" }, :remote  => true do %>
									<span class="glyphicon glyphicon-remove"></span>
								<% end %>
							<% else %>
								<a href="<%=profile_path(comment.profile.id)%>"><span style="clear:both; margin-top: 25px; padding-right: 6px;", class="bold-text"> <%=comment.profile.username%></span></a> <span class="comment-styles"><%=comment.content%></span>
							<% end %>
						</p>
					<% end %>
				</div>
				<p class="time-ago"><%= time_ago_in_words(@post.created_at) %> ago</p>
				<div class="comment-form-container">
					<%= form_for Comment.new, html: { multipart: true, class: "comment-form" }, :remote => true, :authenticity_token => true do |f| %>
						<%= f.text_area :content, placeholder: "Add a comment...", class: "comment-text-area", id: "comment-text-area-#{@post.id}" %>
						<%= f.hidden_field :post_id, :value => @post.id %>
						<%= f.hidden_field :profile_id, :value => current_profile.id %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/vote.js.erb
<% if current_profile.liked? @post %>
	$(".like-btn" + <%= @post.id %>).addClass("liked");
<% else %>
	$(".like-btn" + <%= @post.id %>).removeClass("liked");
<% end %>
$(".likes-count-" + <%= @post.id %>).html("<%=@post.get_upvotes.size%> <%="like".pluralize(@post.get_upvotes.size)%>");